Update and restructure of hackweek roles pages
uwhackweek/hackweeks-as-a-service pull request #35
Opened 2023-01-10 22:36 UTC by aaarendt

This PR is a suggested update to our pages describing roles. I wanted to simplify things and make it easier for newcomers to quickly find a place in what we are doing. Main changes:

* a new index page that replaces our "org chart" with a simple table structure separated out by eScience and client roles. Each category has icons to communicate roles in non-text format
* separates out each role in its own page
* each roles page follows the same structure (goals, specific tasks)

Looking for feedback and there are still a couple of technical glitches. I'd also welcome people in various roles to add images and edit the text.

2023-01-10 22:43 UTC, aaarendt commented
@JessicaS11 I'm remembering your work on [badge like roles](https://github.com/uwhackweek/hackweeks-as-a-service/issues/20). If we like this new format then I'll work on reintroducing that in a future edit.

2023-01-11 00:27 UTC, jomey reviewed
Like the new breakdown and ease of navigation.
All comments are stylistic suggestions.

2023-01-11 00:27 UTC, jomey commented on docs/services/budget-manager.md
> +* notify hackweek organizers of potential funding sources
For style consistency, should the first words in this bullet list be capitalized to match the `Goals` from above?

2023-01-11 00:27 UTC, jomey commented on docs/services/collaboration-architect.md
> +
Style comment: The paragraph uses a mix and match of one and two spaces after a comma.

2023-01-11 00:27 UTC, jomey commented on docs/services/collaboration-architect.md
> +## Range of Activities
Suggest: Range of Hackweek Activites

Then remove 'Hackweek' from below sub-headings.

2023-01-11 00:27 UTC, jomey commented on docs/services/budget-manager.md
> +* notify hackweek organizers of potential funding sources
Note: This is also inconsistent in other role descriptions.

2023-01-13 15:40 UTC, JessicaS11 commented on docs/services/index.md
> +:::{grid-item-card} [Client Roles](#community-roles)
this link doesn't work in the rendered version

2023-01-13 15:45 UTC, JessicaS11 commented on docs/services/index.md
> +* [Tutorial Lead](tutorial-developer.md)
```suggestion
* [Tutorial Leads](tutorial-developer.md) 
```

Since we have multiple...

2023-01-13 15:46 UTC, JessicaS11 commented on docs/services/index.md
> +* [Project Lead](project-lead.md)
```suggestion
* [Project Leads](project-lead.md) 
```

2023-01-18 22:44 UTC, naclomi requested changes
Here are some comments for the educational consultant role

2023-01-18 22:44 UTC, naclomi commented on docs/services/education-consultant.md
> +## Goals
Here are some reworded goals getting a little closer to framing things in terms of learning outcomes and effectiveness. Let me know if you think this covers it, or there is more to articulate:

* Helping all participants feel able to intellectually engage in the educational and project spaces at hackweeks.
* Helping tutorial leads build content that is effective for participants across a wide range of backgrounds and experience levels.

2023-01-18 22:44 UTC, naclomi commented on docs/services/education-consultant.md
> +* Facilitate peer feedback sessions for hackweek tutorial leads as they develop content.
Add:

* Provide content editing with a pedagogical lens for tutorial leads as they develop written content.

2023-01-18 22:44 UTC, naclomi commented on docs/services/education-consultant.md
> +
We can include the learning zones diagram (my favorite ;) ) as a photo here:
![image](https://user-images.githubusercontent.com/1154958/213310938-90671253-936a-408f-9e11-42146e18487b.png)

2023-01-18 22:44 UTC, naclomi commented on docs/services/education-consultant.md
> +
Here's another photo that might fit, from one of my earlier teaching experiences. I think it captures the terror of being a tutorial lead quite nicely. And we can help with that!
![Naomi teaching](https://nlalterman.com/static/in_class_2.jpg)

2023-01-25 20:11 UTC, JessicaS11 commented on docs/services/lead-community.md
> +The Lead Hackweek Coordinator for Community guides the activities of community members engaged in hackweek organization. This is typically the person who contacted eScience requesting a hackweek.
```suggestion
The Lead Hackweek Coordinator for Community guides the activities of community members engaged in hackweek organization and execution. This is typically the person who contacted eScience requesting a hackweek.
```

2023-01-25 20:14 UTC, JessicaS11 commented on docs/services/lead-community.md
> +* Strategizing on how best to implement practices of open source science for this community.
```suggestion
* Strategizing on how best to implement practices of open source science within this community. 
```

2023-01-25 20:22 UTC, JessicaS11 commented on docs/services/lead-community.md
> +* Attend the event and be available to assist with project and tutorial work.
```suggestion
* Acquire funding to support hackweek activities.
* Work with the community to define the overarching goals of the hackweek.
* Build a diverse, inclusive, and equitable hackweek organizing team; recruit broadly for organizers and participants.
* Help organize and attend event planning meetings.
* Review tutorial content, evaluating meeting hackweek goals, learning objectives, and community relevance.
* Attend the hackweek and be available to assist with project and tutorial work.
* Facilitate and/or lead longer-term community efforts to build on collaborations fostered around the hackweek.
```

2023-01-27 03:22 UTC, merged